### ISSUE TITLE
Preferred way to add FunctionalSwift dependency

### ISSUE THREAD

**Issue by hcamatthew** [HCA-Healthcare/FunctionalSwift#1]
Wondering what the preferred way of adding this as a dependency to my project would be?

**Comment by BandoKal** [comment]
There should be a document that we could read that would tell us what the repository is and how to use it... 🤪

**Comment by matthewsramsden** [comment]
Call it iRead

**Comment by BandoKal** [comment]
Added Readme document with cocoapods and carthage instructions
